### PR TITLE
Add SameSite in Cookie struct

### PR DESCRIPTION
**Pull request by 0uep**
Go source code v1.15 contains SameSite: https://golang.org/src/net/http/cookie.go

Also remove unnecessary code source indentation.

### CODE REVIEW

**Review by JanGalek — APPROVED** [review]

**Review by luis33338 — APPROVED** [review]
Master

**Review by luis33338 — COMMENTED** [review]
-

**Comment by luis33338** [comment]
> Master

**Comment by luis33338** [comment]
Master

2491845592

**Pull request merged**
