### PR TITLE
Merged back changes from forked project

### PR DESCRIPTION
**Pull request by thewhitetulip**
I have forked the Go fundamentals chapters from this project into my own tutorial, http://github.com/thewhitetulip/web-dev-golang-anti-textbook/. as per Issue #702 Merging them back to the parent project. It gives me immense pleasure to contribute back to the parent project.

Thank you very much for writing this tutorial! 👍

### CODE REVIEW

**Comment by vCaesar** [comment]
Modified so much.To be or not to be,that is a question.

**Comment by thewhitetulip** [comment]
@vCaesar I am sorry, do not understand what you want to say.

**Comment by vCaesar** [comment]
@thewhitetulip I think a lot has changed,Do not know whether to maintain the book style.

**Comment by thewhitetulip** [comment]
That's why I had asked if you guys want a PR in #702

**Comment by astaxie** [comment]
@thewhitetulip Just review some stuff of the improvement. it has a big change from original version. I think I will keep the old style to keep all the mulit language version the same. Thanks so much

**Comment by thewhitetulip** [comment]
You are welcome @astaxie, I understand that a lot has been changed, thank you for writing this tutorial!

**Pull request closed without merging**
